version: '3.3'
services:
  app:
    build: .
    container_name: kappashiro-bot
    ports:
      - '5555:5555'
    environment:
      - TZ=America/Sao_Paulo
      - ENV_PROD=1
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '5'
    restart: unless-stopped
